kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - sh build.sh
  - name: push-image
    image: plugins/docker
    settings:
      repo: kaners/glytics
      username:
        from_secret: docker_name
      password:
        from_secret: docker_secret
  - name: deploy-image
    image: appleboy/drone-ssh
    environment:
      DB_CONNECTION: 
        from_secret: connection_string
      RECAPTCHA:
        from_secret: recaptcha
    settings:
      host:
        from_secret: ssh_address
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      secrets:
        - DB_CONNECTION
        - RECAPTCHA
      envs: [DB_CONNECTION, RECAPTCHA]
      script:
        - export connection_string=$DB_CONNECTION
        - export recaptcha_glytics=$RECAPTCHA
        - docker stop glytics && docker rm glytics
        - docker pull kaners/glytics
        - docker run -d -p 30011:5000 -p 30012:5001 --env connection_string --env recaptcha_glytics -e API_URL=https://app.g-lytics.com --name glytics kaners/glytics:latest